from pathlib import Path

import pendulum  # type: ignore
from airflow.providers.amazon.aws.hooks.s3 import S3Hook  # type: ignore
from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor  # type: ignore
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator  # type: ignore
from airflow.providers.postgres.hooks.postgres import PostgresHook  # type: ignore
from airflow.sdk import dag, task  # type: ignore

BUCKET = "yt-gcc-183749090090"
AWS_CONN = "aws_s3_conn"
DATA_DIR = "/opt/airflow/data"
PG_CONN = "warehouse_db"


@dag(
    dag_id="yt_warehouse",
    schedule="@daily",
    start_date=pendulum.datetime(2026, 9, 2, tz="UTC"),
    catchup=True,
    max_active_runs=1,
    template_searchpath="/opt/airflow/sql",
)
def yt_warehouse():
    # Wait until the daily processed file is available before starting the load.
    check_file = S3KeySensor(
        task_id="check_file",
        aws_conn_id=AWS_CONN,
        bucket_name=BUCKET,
        bucket_key="processed/youtube/most_popular/ingest_date={{ ds }}/most_popular.ndjson",
        poke_interval=30,
        timeout=300,
    )

    @task
    def download_file(ds=None):
        key = f"processed/youtube/most_popular/ingest_date={ds}/most_popular.ndjson"
        local_dir = f"{DATA_DIR}/ingest_date={ds}"

        Path(local_dir).mkdir(parents=True, exist_ok=True)

        # S3Hook will not overwrite an existing destination; remove stale or partial downloads first.
        (Path(local_dir) / "most_popular.ndjson").unlink(missing_ok=True)

        s3hook = S3Hook(aws_conn_id=AWS_CONN)

        s3hook.download_file(
            key=key,
            bucket_name=BUCKET,
            local_path=local_dir,
            preserve_file_name=True,
            use_autogenerated_subdir=False,
        )

    @task
    def load_raw(ds=None):
        # Replace this date's raw rows so rerunning the DAG does not duplicate them.
        db_path = f"/data/ingest_date={ds}/most_popular.ndjson"
        hook = PostgresHook(postgres_conn_id=PG_CONN)

        hook.run(
            "DELETE FROM staging.raw_landing",
            parameters=(ds,),
        )

        hook.run(
            f"""
            COPY staging.raw_landing (data)
            FROM '{db_path}'
            WITH (FORMAT csv, QUOTE E'\\b', DELIMITER E'\\t')
            """
        )

        hook.run(
            """
            UPDATE staging.raw_landing
            SET ingest_date = %s, source_file = %s
            WHERE ingest_date IS NULL
            """,
            parameters=(
                ds,
                f"processed/youtube/most_popular/ingest_date={ds}/most_popular.ndjson",
            ),
        )

    # Run the warehouse transformations in dependency order; dimensions can load in parallel.
    load_staging = SQLExecuteQueryOperator(
        task_id="load_staging",
        conn_id=PG_CONN,
        sql="01_staging.sql",
    )

    load_dim_type1 = SQLExecuteQueryOperator(
        task_id="load_dim_type1",
        conn_id=PG_CONN,
        sql="02_dim_type1.sql",
    )

    load_dim_type2 = SQLExecuteQueryOperator(
        task_id="load_dim_type2",
        conn_id=PG_CONN,
        sql="03_dim_type2.sql",
    )

    load_bridge = SQLExecuteQueryOperator(
        task_id="load_bridge",
        conn_id=PG_CONN,
        sql="04_bridge.sql",
    )

    load_fact = SQLExecuteQueryOperator(
        task_id="load_fact",
        conn_id=PG_CONN,
        sql="05_fact.sql",
    )

    run_checks = SQLExecuteQueryOperator(
        task_id="run_checks",
        conn_id=PG_CONN,
        sql="06_checks.sql",
    )

    check_file >> download_file() >> load_raw() >> load_staging

    load_staging >> [load_dim_type1, load_dim_type2]
    load_dim_type2 >> load_bridge
    [load_dim_type1, load_bridge] >> load_fact >> run_checks


yt_warehouse()